name: First CI

on:
  push:
    branches:
      - main
env:
  POSTGRES_DB: ${{ secrets.CI_POSTGRES_DB }}
  POSTGRES_USER: ${{ secrets.CI_POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.CI_POSTGRES_PASSWORD }}
  DB_HOST: db
  DB_NAME: ${{ secrets.CI_POSTGRES_DB }}
  DB_USER: ${{ secrets.CI_POSTGRES_USER }}
  DB_PASSWORD: ${{ secrets.CI_POSTGRES_PASSWORD }}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest



    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Prepare image name
        id: image-name
        run: |
          IMAGE_NAME="ghcr.io/${GITHUB_REPOSITORY,,}":${GITHUB_SHA}
          echo "image=$IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Build and push app image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.image-name.outputs.image }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create build info
        run: |
          {
            echo "Commit= $GITHUB_SHA"
            echo "Repository= $GITHUB_REPOSITORY"
            echo "Runner OS= $RUNNER_OS"
            echo "Image= ${{ steps.image-name.outputs.image }}"
            echo "Build date= $(date -u)"
          } > build-info.txt
        
      - name: Upload build info
        uses: actions/upload-artifact@v4
        with:
          name: build-info
          path: build-info.txt
    
    outputs:
      image: ${{ steps.image-name.outputs.image }}
  
  integration-test:
    runs-on: ubuntu-latest
    needs: build
    env:
      POSTGRES_DB: ${{ secrets.CI_POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.CI_POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.CI_POSTGRES_PASSWORD }}
      DB_HOST: db
      DB_NAME: ${{ secrets.CI_POSTGRES_DB }}
      DB_USER: ${{ secrets.CI_POSTGRES_USER }}
      DB_PASSWORD: ${{ secrets.CI_POSTGRES_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build info
        uses: actions/download-artifact@v4
        with:
          name: build-info
      
      - name: Show build info
        run: cat build-info.txt

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN}}
    
      - name: Start stack
        env:
          APP_IMAGE: ${{ needs.build.outputs.image }}
        run: docker compose up -d --scale app=2
      
      - name: Show containers
        run: docker compose ps
      
      - name: Wait for stack
        run: sleep 10
      
      - name: Check health through nginx
        run: curl -f localhost:8090/health
      
      - name: Check readiness through nginx
        run: curl -f localhost:8090/ready
      
      - name: Show logs on failure
        if: failure()
        run: docker compose logs
      
      - name: Stop stack
        if: always()
        run: docker compose down -v

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
      - integration-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    environment:
      name: production
    
    steps:
      - name: Show deployment information
        run: |
          echo "Deploying image:"
          echo "${{ needs.build.outputs.image }}"
          echo "Commit:"
          echo "$GITHUB_SHA"
      
      - name: Simulate production deployment
        run: |
          echo "Deployment started"
          sleep 5
          echo "Deployment completed"